#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Anh Tuan Nguyen Resume
url: 'https://anhtuank7c.github.io'
baseurl:  #change it according to your repository name
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
pic: https://github.com/anhtuank7c.png
description: |
  I'm 30 years old Freelancer and Community Administrator of React Native Viet Nam and senior developer from the cozy street of Ha Noi.
  I have more than 8 years of work experience in various positions.
  I love coding, music and swimming, football, playing PUBG.
  My visionary believed that teamwork is essential to delivering great software.
  I am very strong in React Native.

# Tracker
analytics: UA-128129447-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Build sitemap
plugins:
  - jekyll-sitemap

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
